### PR TITLE
FW/Tests: Allow test lists to specify different times for each test

### LINKED ISSUE #533: Timing in timed test lists not applied per test
Given
```
$ cat testlist
selftest_timedpass:10
selftest_timedpass:150
$ ./opendcdiag --selftests -o - --test-list-file testlist
```

Before e89cd594fcda062209c3fccf7fa7a34bbe62b58f:
```yaml
tests:
- test: selftest_timedpass
  details: { quality: beta, description: "Loops around usleep() for the regular test time" }
  state: { seed: 'AES:6191e47dc78fde56624e4f956cd34fa79e6e1b82387021a99db1b06a932cb058', iteration: 0, retry: false }
  time-at-start: { elapsed:      0.000, now: !!timestamp '2024-07-19T15:36:06Z' }
  result: pass
  time-at-end:   { elapsed:     11.999, now: !!timestamp '2024-07-19T15:36:06Z' }
  test-runtime: 12.626
- test: selftest_timedpass
  details: { quality: beta, description: "Loops around usleep() for the regular test time" }
  state: { seed: 'AES:16ac70e7a580c1b6a0dd66f99c6825609e6e1b82387021a99db1b06a932cb058', iteration: 0, retry: false }
  time-at-start: { elapsed:     18.999, now: !!timestamp '2024-07-19T15:36:06Z' }
  result: pass
  time-at-end:   { elapsed:    170.998, now: !!timestamp '2024-07-19T15:36:06Z' }
  test-runtime: 153.249
# Loop iteration 1 finished, average time 177.52 ms, total 177.52 ms
- test: mce_check
  details: { quality: production, description: "Machine Check Exceptions/Events count" }
  state: { seed: 'AES:bf2d9c0ec73a3f6e966665d97ddabfe19e6e1b82387021a99db1b06a932cb058', iteration: 0, retry: false }
  time-at-start: { elapsed:    170.998, now: !!timestamp '2024-07-19T15:36:06Z' }
  result: pass
  time-at-end:   { elapsed:    173.998, now: !!timestamp '2024-07-19T15:36:06Z' }
  test-runtime: 3.014
exit: pass
```

After:
```yaml
tests:
- test: selftest_timedpass
  details: { quality: beta, description: "Loops around usleep() for the regular test time" }
  state: { seed: 'AES:fffc3604d9ed0812a430e2fd185cec390003c9fb2612f7ed5bcf1d02e7a313c6', iteration: 0, retry: false }
  time-at-start: { elapsed:      0.000, now: !!timestamp '2024-07-19T15:33:02Z' }
  result: pass
  time-at-end:   { elapsed:    160.000, now: !!timestamp '2024-07-19T15:33:02Z' }
  test-runtime: 158.627
- test: selftest_timedpass
  details: { quality: beta, description: "Loops around usleep() for the regular test time" }
  state: { seed: 'AES:591e97287c944c87dbd4541f097192020003c9fb2612f7ed5bcf1d02e7a313c6', iteration: 0, retry: false }
  time-at-start: { elapsed:    163.333, now: !!timestamp '2024-07-19T15:33:02Z' }
  result: pass
  time-at-end:   { elapsed:    326.667, now: !!timestamp '2024-07-19T15:33:02Z' }
  test-runtime: 160.658
# Loop iteration 1 finished, average time 325.254 ms, total 325.254 ms
exit: pass
```

The lack of `mce_check` is irrelevant for now.

The timing of 150 ms was applied to both runs of the test, not to each test like it used to be.

### PR DESCRIPTION
**Pull request by thiagomacieira**
This refactors `SandstoneTestSet` to keep extra options in each test that is added to the roster. The only one for the moment is the requested duration, but this allows expanding later as needed. This restores the behaviour prior to e89cd594fcda062209c3fccf7fa7a34bbe62b58f.

Fixes #533.

### CODE REVIEW

File: framework/sandstone_tests.cpp [hunk 1]
```diff
@@ -79,51 +79,42 @@ SandstoneTestSet::SandstoneTestSet(struct test_set_cfg cfg, unsigned int flags)
...
+{
+    auto it = std::remove_if(test_set.begin(), test_set.end(), [&](const test_cfg_info &ti) {
+        return ti.test == test;
+    });
+    test_set.erase(it, test_set.end());
 }
 
-std::vector<struct test_cfg_info> SandstoneTestSet::disable(const char *name) {
-    std::vector<struct test_cfg_info> res;
+void SandstoneTestSet::disable(const char *name)
```
Comment (busykai) [inline framework/sandstone_tests.cpp:112]: Do not remove the return value. I know it is not being used now, but the plan was to improve diagnostics to warn that names didn't match any.

Comment (busykai) [inline framework/sandstone_tests.cpp:112]: Let's call this `remove` as well. It effectively does removal by name or pattern.

File: framework/sandstone_tests.cpp [hunk 2]
```diff
@@ -79,51 +79,42 @@ SandstoneTestSet::SandstoneTestSet(struct test_set_cfg cfg, unsigned int flags)
...
         ti.status = test_cfg_info::enabled;
         ti.test = &test;
-        test_map[test.id] = ti;
         test_set.push_back(&test);
     }
 };
 
-struct test_cfg_info SandstoneTestSet::enable(struct test *t) {
-    struct test_cfg_info &ti = test_map[t->id];
+struct test_cfg_info SandstoneTestSet::append(test_cfg_info t)
```
Comment (busykai) [inline framework/sandstone_tests.cpp:86]: I was thinking that maybe `add()` would be a better name. I know it adds it to the end and therefore appends, but add/remove dichotomy is more cleaner in this case, IMO.

File: framework/sandstone.cpp [hunk 3]
```diff
@@ -3814,7 +3822,7 @@ int main(int argc, char **argv)
     // a multi-socket system, it's done after the main run and only using the
     // failing tests.
     SandstoneApplication::PerCpuFailures per_cpu_failures;
-    vector<const struct test *> triage_tests;
+    std::vector<test_cfg_info> triage_tests;
```
Comment (busykai) [inline framework/sandstone.cpp:3825]: BTW, we need to remove `triage`, see #530

**Review by busykai — COMMENTED** [review]
Left a few comments. I think we also need to rename `enable(struct test*)` to `add(struct test*)` (or `append()`).

File: framework/sandstone.cpp (hunk 3 above)
Comment (thiagomacieira) [reply framework/sandstone.cpp]: Yup.

File: framework/sandstone_tests.cpp (hunk 2 above)
Comment (thiagomacieira) [reply framework/sandstone_tests.cpp]: Ok.

File: framework/sandstone_tests.cpp (hunk 1 above)
Comment (thiagomacieira) [reply framework/sandstone_tests.cpp]: For that you don't need a list of tests that did match. You just need a count, because `name` is what you want to warn on.

Changing to return the count of disabled tests.

Comment (thiagomacieira) [reply framework/sandstone_tests.cpp]: Counterpart to `enable` so keeping the name.

File: framework/sandstone.cpp (hunk 3 above)
Comment (thiagomacieira) [reply framework/sandstone.cpp]: Approved, merged, rebased on top of that.

**Comment by thiagomacieira** [comment]
> Left a few comments. I think we also need to rename `enable(struct test*)` to `add(struct test*)` (or `append()`).

I'll submit a separate PR after this with the renaming.

**Review by busykai — APPROVED** [review]
