### PR TITLE
FW/Unix: fix handling of signals in wait_for_children()

### LINKED ISSUE #429: Framework restarts the test after a signal is received
This a regression since b7dbacbdb2c509a26ced509dad93389003d1f974 or thereabouts.

### Test
```sh
./opendcdiag --selftests -e selftest_timedpass_busywait -o - & 
sleep 0.1
kill -INT %+
wait
```

### Expected behaviour
OpenDCDiag exits immediately, reports "exit: interrupted" and re-raises the signal that interrupted it.
```
tests:
- test: selftest_freeze
  details: { quality: beta, description: "Freezes" }
  state: { seed: 'AES:8935d753c2767a50eed11b84ca99b5f376ca28ac3d8985af112ee47b35664a0c', iteration: 0, retry: false }
  time-at-start: { elapsed:      0.000, now: !!timestamp '2023-10-12T23:59:13Z' }
# Caught SIGINT, stopping current test (press Ctrl+C again to exit without waiting)                                                                              
  result: interrupted
  fail: { cpu-mask: null, time-to-fail: null, seed: 'AES:8935d753c2767a50eed11b84ca99b5f376ca28ac3d8985af112ee47b35664a0c'}
  time-at-end:   { elapsed:     97.999, now: !!timestamp '2023-10-12T23:59:13Z' }
  test-runtime: 97.508
exit: interrupted
[2]  + interrupt  ./opendcdiag --selftests -e selftest_freeze -Y -o -
```

### Actual behaviour
The current test is terminated but it is restarted again, for retesting, leading to "exit: fail" and exit code 1 instead.
```
$ ./opendcdiag --selftests -e selftest_timedpass_busywait -o - --retest-on-failure=1 & sleep 0.1; kill -INT %+; fg
...
tests:
- test: selftest_timedpass_busywait
  details: { quality: beta, description: "Runs for the requested time, but busy-waiting" }
  state: { seed: 'AES:5a1081f8f55be6ea4cab76a4f271e845a5ef7e070aa41915b354895b0d8e17ba', iteration: 0, retry: false }
  time-at-start: { elapsed:      0.000, now: !!timestamp '2023-10-12T23:58:01Z' }
[1]  + 3638813 running    ./opendcdiag --selftests -e selftest_timedpass_busywait -o - 
# Caught SIGINT, stopping current test (press Ctrl+C again to exit without waiting)
  result: crash
  result-details: { crashed: true, core-dump: false, code: 2, reason: 'Interrupt' }
  fail: { cpu-mask: null, time-to-fail: null, seed: 'AES:5a1081f8f55be6ea4cab76a4f271e845a5ef7e070aa41915b354895b0d8e17ba'}
  time-at-end:   { elapsed:     83.333, now: !!timestamp '2023-10-12T23:58:01Z' }
  test-runtime: 80.739
- test: selftest_timedpass_busywait
  details: { quality: beta, description: "Runs for the requested time, but busy-waiting" }
  state: { seed: 'AES:5a1081f8f55be6ea4cab76a4f271e845a5ef7e070aa41915b354895b0d8e17ba', iteration: 1, retry: true }
  time-at-start: { elapsed:     83.333, now: !!timestamp '2023-10-12T23:58:01Z' }
  result: pass
  time-at-end:   { elapsed:    283.333, now: !!timestamp '2023-10-12T23:58:01Z' }
  test-runtime: 200.283
- test: selftest_timedpass_busywait
  details: { quality: beta, description: "Runs for the requested time, but busy-waiting" }
  state: { seed: 'AES:5a1081f8f55be6ea4cab76a4f271e845a5ef7e070aa41915b354895b0d8e17ba', iteration: 2, retry: true }
  time-at-start: { elapsed:    283.333, now: !!timestamp '2023-10-12T23:58:01Z' }
  result: pass
  time-at-end:   { elapsed:    483.334, now: !!timestamp '2023-10-12T23:58:01Z' }
  test-runtime: 200.275
# Test failed 1 out of 3 times (33.3%)
# Topology analysis:
# Loop iteration 1 finished, average time 481.528 ms, total 481.528 ms
triage-results: [ 0 ]
exit: fail
```

### PR DESCRIPTION
**Pull request by thiagomacieira**
The rewrite in commit 37cb3e5404eea2847c5da5fe576be0268282b8ee for wait_for_children() accidentally broke the handling of interruptions by signals on Unix systems, which exists to ensure all the processes get interrupted if the parent process is.

Handling of SIGHUP and SIGTERM was easy, since single_wait() was already returning the correct signal number, but wait_for_all_children() wasn't acting on it. Handling of SIGINT required remembering we had been interrupted once.

Fixes #429.

### CODE REVIEW

**Comment by thiagomacieira** [comment]
Testing indicates a multi-children crash blames the wrong thread:
```yaml
  test-plans:
    fullsocket: [ { starting_cpu: 0, count: 2 }, { starting_cpu: 2, count: 2 } ]
    heuristic: [ { starting_cpu: 0, count: 1 }, { starting_cpu: 1, count: 1 }, { starting_cpu: 2, count: 1 }, { starting_cpu: 3, count: 1 } ]
  tests:
  - test: selftest_sigsegv_socket1
    details: { quality: beta, description: "Crashes with SIGSEGV (data) dereferencing the null page for any thread of socket 1" }
    state: { seed: 'LCG:1100863826', iteration: 0, retry: false }
    time-at-start: { elapsed:      0.000, now: !!timestamp '2023-10-19T23:32:57Z' }
    result: crash
    result-details: { crashed: true, core-dump: false, code: 0xc0000005, reason: 'Access violation' }
    fail: { cpu-mask: 'X.:..', time-to-fail: null, seed: 'LCG:1100863826'}
    time-at-end:   { elapsed:     54.479, now: !!timestamp '2023-10-19T23:32:57Z' }
    test-runtime: 54.361
    threads:
    - thread: 0
      id: { logical-group:  0, logical:  0, package: 0, core: 0, thread: 0, family: 6, model: 0x3c, stepping: 0, microcode: null, ppin: null }
      state: failed
      time-to-fail: 52.508
      loop-count: 0
      messages:
      - { level: error, text: 'E> Received exception 0xc0000005 (Access violation), RIP = 0x7ff6464699bc (base+0x299bc), CR2 = 0x645 access=R' }
      - level: info
        text: |1
         Registers:
          rax   = 0x0000000000000645 (1605)
          rbx   = 0x0000000000000000 (0)
          rcx   = 0x0000000000000645 (1605)
          rdx   = 0x0000014d2a6f6e80
          rsi   = 0x0000014d2a6f2050
          rdi   = 0x0000000000000000 (0)
          rbp   = 0x0000002d00fff620
          rsp   = 0x0000002d00fff620
          r8    = 0x0000002d00fff5c8
          r9    = 0x0000000000000000 (0)
          r10   = 0x0000000000000000 (0)
          r11   = 0x0000002d00fff670
          r12   = 0x0000000000000000 (0)
          r13   = 0x0000000000000000 (0)
          r14   = 0x0000000000000000 (0)
          r15   = 0x0000000000000000 (0)
          rip   = 0x00007ff6464699bc
          flags = 0x00010202 [ IF RF ]
          fs    = 0x53
          gs    = 0x2b
          fcw   = 0x37f
          fsw   = 0 [ top=0 ]
          ftw   = 0
          mxcsr = 0x00001f80 [ IM DM ZM OM UM PM RC=nearest ]
          ymm0  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm1  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm2  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm3  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm4  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm5  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm6  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm7  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm8  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm9  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm10 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm11 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm12 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm13 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm14 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm15 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
      - { level: error, text: 'E> Received exception 0xc0000005 (Access violation), RIP = 0x7ff6464699bc (base+0x299bc), CR2 = 0xdc2 access=R' }
      - level: info
        text: |1
         Registers:
          rax   = 0x0000000000000dc2 (3522)
          rbx   = 0x0000000000000000 (0)
          rcx   = 0x0000000000000dc2 (3522)
          rdx   = 0x000001dbc5f96ec0
          rsi   = 0x000001dbc5f92060
          rdi   = 0x0000000000000000 (0)
          rbp   = 0x000000488a3ff8b0
          rsp   = 0x000000488a3ff8b0
          r8    = 0x000000488a3ff858
          r9    = 0x0000000000000000 (0)
          r10   = 0x0000000000000000 (0)
          r11   = 0x000000488a3ff900
          r12   = 0x0000000000000000 (0)
          r13   = 0x0000000000000000 (0)
          r14   = 0x0000000000000000 (0)
          r15   = 0x0000000000000000 (0)
          rip   = 0x00007ff6464699bc
          flags = 0x00010202 [ IF RF ]
          fs    = 0x53
          gs    = 0x2b
          fcw   = 0x37f
          fsw   = 0 [ top=0 ]
          ftw   = 0
          mxcsr = 0x00001f80 [ IM DM ZM OM UM PM RC=nearest ]
          ymm0  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm1  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm2  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm3  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm4  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm5  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm6  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm7  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm8  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm9  = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm10 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm11 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm12 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm13 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm14 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
          ymm15 = 0000000000000000:0000000000000000 0000000000000000:0000000000000000
```

File: framework/sandstone.cpp [hunk 1]
```diff
@@ -1553,7 +1553,7 @@ static void wait_for_children(ChildrenList &children, int *tc, const struct test
     children.pollfds.emplace_back(pollfd{ .fd = sApp->shmem->server_debug_socket, .events = POLLIN });
     auto remove_debug_socket = scopeExit([&] { children.pollfds.pop_back(); });
 
-    auto single_wait = [&](milliseconds timeout) {
+    auto single_wait = [&, caughtSignal = 0](milliseconds timeout) mutable {
```
Comment (jposwiata) [inline framework/sandstone.cpp:1556]: simple conditions (timeout '==0', signal '<0' and event otherwise, with clear returns) would be simpler to read/understand.

**Review by jposwiata — DISMISSED** [review]
This is 'quick fix' to handle 'immediate' signals. Fix is valid.
As there's no SIGINT handling ("overall"), more discussion/work is required (best would be another tasks).

**Comment by dawid-sabat** [comment]
I verified this fix on my end as well.

File: bats/sanity-check/20-selftests.bats [hunk 2]
```diff
@@ -1525,3 +1525,50 @@ selftest_cpuset_unsorted() {
...
+    $SANDSTONE -Y -o - -n1 --max-test-loop-count=0 --selftests -e selftest_timedpass -t $timeout > $yamlfile &
+    local pid=$!
+
+    # let's wait for the test to actually start
+    sleep 1
+
+    kill -$signal $pid
+    if wait $!; then
+        # Confirm it was the correct signal
+        (( $? = 128 | $(kill -l $signal)))
```
Comment (thiagomacieira) [inline bats/sanity-check/20-selftests.bats]: Oops, this needs to be `==`

**Comment by dawid-sabat** [comment]
I see a problem when we run opendcdiag with `--service` parameter. In such case the framework doesn't quit gracefully. 
(to reproduce give it some time to start running actual tests).
We might have found this issue #157

File: framework/sandstone.cpp [hunk 3]
```diff
@@ -1606,7 +1609,7 @@ static void wait_for_children(ChildrenList &children, int *tc, const struct test
             children.results[i].usage = usage;
             --children_left;
         }
-        return 0;
+        return caughtSignal;
```
Comment (jposwiata) [inline framework/sandstone.cpp:1615]: This is behavioral change. The execution **will not** continue after ALARM/SEG FAULT/ABORT/etc.
Instead of this additional variable, we can check the overall status and react on Killed/Interrupted with appropriate exit code (if we're allowed to change old Ctrl-C behavior).

**Review by jposwiata — CHANGES_REQUESTED** [review]

File: bats/sanity-check/20-selftests.bats [hunk 4]
```diff
@@ -1525,3 +1525,50 @@ selftest_cpuset_unsorted() {
...
+    # let's wait for the test to actually start
+    sleep 1
+
+    kill -$signal $pid
+    if wait $!; then
+        # Confirm it was the correct signal
+        (( $? == (128 | $(kill -l $signal))))
+    else
+        echo >&2 'Test did not exit!'
+    fi
```
[the remark this answers is not in the document]
Comment (thiagomacieira) [reply bats/sanity-check/20-selftests.bats:1551]: It indeed looks wrong. We're probably running the `else` code all the time, but because this is passing, I didn't notice it. Weirdly, I can't debug this because if I add a `false` after this `if` so it will fail, bats fails completely:
```
1..3
# bats warning: Executed 0 instead of expected 3 tests
```

Changing to fd 3 does show that we're running on the wrong side.

[the remark this answers is not in the document]
Comment (thiagomacieira) [reply bats/sanity-check/20-selftests.bats:1551]: https://github.com/bats-core/bats-core/issues/364 - I need to remove the `trap`

File: framework/sandstone.cpp (hunk 3 above)
Comment (thiagomacieira) [reply framework/sandstone.cpp:1615]: No, that's not the case. Testing does show it works properly. Just run the `selftest_sigsegv` and you'll see it gets retried properly.

This `caughtSignal` here only applies if the parent process gets a signal and only the SIGHUP, SIGINT, SIGTERM, and SIGPIPE signals (`terminationSignals` in unix/signals.cpp). It does not apply to crashing signals or SIGALRM received by the parent process and it does not apply to any signals received by the child processes either.

**Comment by jposwiata** [comment]
> I see a problem when we run opendcdiag with `--service` parameter. In such case the framework doesn't quit gracefully.

This is related to signal handling in waiting. Fixed with https://github.com/opendcdiag/opendcdiag/pull/439

File: framework/sandstone.cpp (hunk 3 above)
Comment (jposwiata) [reply framework/sandstone.cpp:1615]: Sorry, I was wrong, you're right.
Handling here is limited to handle signals from "external" world (sent by the operator or OS, e.g. service termination, Ctrl-C, Ctrl-|, etc), not the ones "automatically sent" (on "critical" issues in test execution).

**Review by jposwiata — APPROVED** [review]
LGTM
